### ISSUE TITLE
Storing protocols that peers support

### ISSUE THREAD

**Issue by Mikerah** [libp2p/js-libp2p-switch#304]
Recently, I created [this issue in js-peer-info](https://github.com/libp2p/js-peer-info/issues/72) about storing protocols that peers support. @jacobheun suggested that js-libp2p-switch needs to be updated to perform `ls` on `multistreams` in order to set an initial protocol list for peers in such a way that this list can be updated later.

**Comment by jacobheun** [comment]
Right now Switch plays dumb and just iterates over all of it's protocols attempting to "negotiate" with a peer. Ideally once we're connected, we should do an `ls` via `multistream-select` to get it's list of protocols to start making informed decisions about which protocols we attempt to use. We can then store the available protocols on the `PeerInfo` object and continue with protocol negotiation by selecting our favored protocols that match what the peer handles, instead of the more expensive negotiation we're doing now.

**Comment by Mikerah** [comment]
I am starting to work on this task in order to continue work on an adjacent project. I am trying to understand what is going on in the code before attempting to change anything.

Here's what I think needs to be done:

- Perform an `ls` in the `_onUpgrading` method in the `ConnectionFSM` class. Specifically, within the `msDialer.handle` callback function. Then store the result in `this.conn`'s `peerInfo.protocols`

- Instead of running `nextMuxer` on `muxers.shift` to negotiate with a peer and determine what protocol to use, we instead iterate over the previously stored protocols and call `nextMuxer` (or some equivalent method) on each protocol.

Am I missing any extra steps?

**Comment by jacobheun** [comment]
Yes, that's should get support added for the dialing node. 

> * Then store the result in `this.conn`'s `peerInfo.protocols`

This should be `this.theirPeerInfo` for the ConnectionFSM.

For listeners, the `ls` logic will need to also be added inside the handle at https://github.com/libp2p/js-libp2p-switch/blob/v0.41.5/src/connection/incoming.js#L99.

It doesn't need to be done now, but the `ls` would likely be best done before crypto negotiation. We don't actually have different cryptos right now and will hopefully move to multistream2.0 before we do, so knowing the supported crypto protocols via the `ls` of the other node up front isn't a big deal.
