### ISSUE TITLE
New and more accurate name for libp2p-swarm

### ISSUE THREAD

**Issue by nicola** [libp2p/js-libp2p-switch#40]
The word swarm keeps on making me think about a set of peers,
while instead this module is not.

Can we find a more appropriate name for this?
(sorry for bringing this up, but this is bothering me!)

**Comment by diasdavid** [comment]
This issue was brought up during the IPFS workshop, I agree that we should change it, it confuses a lot of people.

I propose `net-machine`, as `net` is traditionally the package name available in languages that exposes a `dial/listen` interface + this module really is (needs to be) a state machine to handle all of the concurrent requests for dialing to a peer (or the same peer), upgrading the connection, etc. Also, I think that `net-machine` sounds cool and it is a pretty unique name from everything out there.

I summon the gods of the 🚲 🏠 to come forward and comment here @jbenet @whyrusleeping

**Comment by jbenet** [comment]
I thing this is really a `switch`

**Comment by nicola** [comment]
(what is 🚲 🏠?)

**Comment by dignifiedquire** [comment]
> (what is 🚲 🏠?)

🚲 = bike
🏠  = shed
🚲 🏠  = bikeshedding

**Comment by diasdavid** [comment]
`switch-machine`?

**Comment by nicola** [comment]
- stateful-net
- switch
- dialer

**Comment by jbenet** [comment]
I dont like the name combination `<thing>-machine`, its very big for this sort of thing, this is going into all our code. run any name change through what it would look like in js-ipfs, go-ipfs, go-libp2p, js-libp2p, docs, and so on.

- "swarm" is there because it's "the thing that lets me talk to the swarm", and there are equivalent packages named swarm for bittorrent.

After much thought, I think:
- "switch" is what this part is called in most networking architectures.
- the name is apt, the swarm by itself IS NOT doing connection discovery, it's only doing connection management and information flow (what traditionally switches (inc NICs) do)
- `Switch` works very well with all our code, works as well as `Swarm`.
- `libp2p.Switch` looks excellent.  `libp2p.Router` looks good too
- "switch" is a MUCH more accurate name, that carries all the notion of "the think in a networked computer that handles the low level networking, packet flow, and connections". this thing is doing "circuit switching", and its the [physical machines](https://www.youtube.com/watch?v=xZePwin92cI) and operations at bell that was called "a switch" and "switching" that seeded the name for these devices (hardware or software. 

To put objections that "switch means packets", note that circuit switching came before packet switching, so "switch" is not just about packets.

**Comment by lgierth** [comment]
Aaand the "switch" was supposed to be a distinct component between the swarm and the transport.

Maybe we can come up with a term that carries a manager/controller-type meaning? I liked "dialer", but this is too closely tied to the network libraries we use. We need something that says "I set up connections, maintain them, tear them down, and generally make sure you're part of the swarm".

**Comment by lgierth** [comment]
- circuit

**Comment by jbenet** [comment]
@lgierth watch the video for switches, it's awesome.

The original meaning of "switch" was a circuit switch that kept connections
open. They were pretty smart compared to their internet counter parts.

I'm down to keep looking for other words. And we should think through how
this thing will operate in light of packet switching for sure, before
renaming. Great call

**Comment by diasdavid** [comment]
Juan has won this one, it shall be known as switch now.

Will rename it when time enables.

**Comment by lgierth** [comment]
Yeah switch is good.

Renaming will be a beast though -- do we already have its Core API defined? At least there's HTTP API and CLI functions in go-ipfs that **must** stay available.

**Comment by diasdavid** [comment]
@lgierth trick is exactly that, this is a building block, not the API that is being exposed at the IPFS cli/http api, they just share the same name and after the rename they wont anymore :)

**Comment by lgierth** [comment]
Ugh I don't know... if you and @jbenet have strong opinions about renaming to switch I'm all for it, but doesn't this *not exactly* help with consistency?

What is the swarm that's being referenced in the APIs and CLI then, if not the libp2p swarm?

**Comment by diasdavid** [comment]
Yeah, that is the confusion, the CLI/HTTP API Swarm is not this module. This module is the piece inside libp2p that does all the dialing in parallel to multiple transports, does the connection upgrades and also does the Protocol Muxing.

**Comment by lgierth** [comment]
Okay but was it the swarm on the CLI/HTTP API then? I feel like that's important to define beforehand, otherwise it *will* lead to confusion.

**Comment by diasdavid** [comment]
`Swarm` on the CLI/HTTP API are the network plumbing commands that were created before libp2p existed, they will continue to exist and be supported.

I do have a proposal (to make at some point) that we should just have `ipfs libp2p` or `ipfs p2p`  and expose all the new networking primitives through there.

**Comment by jomarip** [comment]
I am new to the conversation, but I definitely think swarm makes me think of other things. Recently was reading the following for example.
A decentralization approach for swarm intelligence algorithms in networks applied to multi swarm PSO
By: Merkle, Daniel, Janson, Stefan, Middendorf, Martin 
In:   International Journal of Intelligent Computing and Cybernetics
[Multi swarms for neighbor selection in peer-peer overlay networks.pdf](https://github.com/libp2p/js-libp2p-swarm/files/1082938/Multi.swarms.for.neighbor.selection.in.peer-peer.overlay.networks.pdf)

**Comment by diasdavid** [comment]
# [The thing is now called a Switch \o/](https://github.com/libp2p/js-libp2p-switch/pull/242)

Thank you everyone that participated in the discussion :)

**Comment by raulk** [comment]
Reading through this issue as part of the libp2p roadmapping effort for 2019, and I loved the discussion. Just wanted to say that ❤️
